### ISSUE TITLE
Generation job immediate finish

### ISSUE THREAD

**Issue by Avadon** [kartotherian/kartotherian#113]
Greetings everyone,

I have a strange problem when generation job finishes in less 1 second.

![Job screen](https://i.ibb.co/jDWsgTx/Screen-Shot-2019-07-08-at-14-17-27.png)

Example POST request:

 curl -X POST "http://HOSTNAME/add?generatorId=substbasemap&storageId=basemap&zoom=11&fromZoom=11&beforeZoom=12&parts=10&deleteEmpty=true&keepJob=true&checkZoom=-1"

What is the possible reason?

**Comment by thesocialdev** [comment]
@Avadon does it happen in all zoom levels?

A possible reason I have experienced:
- Empty OSM database
- uiOnly [enabled](https://github.com/kartotherian/kartotherian/blob/master/packages/tilerator/config.dev.yaml#L104) 

Maybe @nyurik can have a different perspective.

**Comment by Avadon** [comment]
@thesocialdev thanks for the answer. Yep, I've tried the same on different zoom levels.

Postgis DB was definitely not empty, but I have to mention that in the beginning tile generation was OK. But at some point of time all tile generation jobs started to finish immediately. It would be great to have an option for activating more detailed log.

uiOnly was actually enabled, but only in API container. I use scheme with 2 containers:

```
  tilerator:
    environment:
      - TILERATOR_MODE=api # This service will not process tiles
    volumes:
     - ./tilerator_config:/etc/tilerator
     - ./update_tiles_data:/data/update_tiles_data

  tilerator-worker:
    environment:
      - TILERATOR_NUM_WORKERS=ncpu # Number of workers (or ncpu by default)
    volumes:
     - ./tilerator_config:/etc/tilerator
```
