### ISSUE TITLE
Refactor configuration system

### ISSUE THREAD

**Issue by nyurik** [kartotherian/kartotherian#95]
Kartotherian has outgrown its current configuration/modular system, and needs to be rethought. Existing configuration [example](https://github.com/kartotherian/kartotherian/blob/master/sources.prod2.yaml). Ideally, we may be able to engage larger tilelive community to consider revising the existing interface towards a more generic Promise-based one.

# Requirements
* Support existing [tilelive ecosystem](https://github.com/mapbox/tilelive). Each tilelive module is instantiated with a URI, whose protocol identifies which constructor to use. The modules register their protocols with the common tilelive registry. Each instance has a `getTile(z,x,y,callback)` function that returns [data, headers] via callback.
* Tilelive interface only passes 3 params: zoom,x,y, but often more context is needed (e.g. user's language, license key, ...). The new interface should have a more generic `<Promise<object>> get(<object>)`. If the module has old interface, the `get()` should be injected. If the module only supports the new interface, the old functions should be injected so that it can be used with other tilelive code.
* Some modules do not have a tilelive interface, but can consume it. For example, a snapshot module can combine multiple tiles into a single image.
* Module loader should be able to mix and match modules via configuration. Example configurations:
  * configure renderer (moduleA) with data coming from storage (moduleB)
  * same as above, but moduleB is a demultiplexer, which takes tiles from multiple different modules
  * a geodata processing module that runs some queries directly on Postgress DB and produces geojson
  * an image snapshot service module that uses a tile module to get data, and geodata module to create overlays

# Implementation Ideas
* Match every existing tilelive function with an Async version:
    `getTile(z, x, y, callback)`  &rarr;  `<Promise<object>> getTileAsync(object)`, with the assumption that object parameter will have `z, x, y` values.  The loader will inject a wrapper function if either `getTile` or `getTileAsync` is missing.

# YAML config file structure
* Tile requests: src, z, x, y, [scale], format
`/:src([A-Za-z][-A-Za-z0-9_]*)/:z(\\d+)/:x(\\d+)/:y(\\d+):scale(@[\\.\\d]+x)?.:format([\\w]+)`
* Geodata requests
`/geoshape?...`, `/geoline?...`, `/shape?...`
* Snapshot requests: src, zoom, lat, lon, w, h, [scale], format, [query params]. May use tile and geodata services.
`/img/:src([A-Za-z][-A-Za-z0-9_]*),:zoom(a|\\d+),:lat(a|[-\\d\\.]+),:lon(a|[-\\d\\.]+),:w(\\d+)x:h(\\d+):scale(@[\\.\\d]+x)?.:format([\\w]+)`

```yaml
routes:
  # List of route objects
  - route:
    # The route param is a string or a list of routes as accepted by express
    - "/img/:src([A-Za-z][-A-Za-z0-9_]*),:zoom(a|\\d+),:lat(a|[-\\d\\.]+),:lon(a|[-\\d\\.]+),:w(\\d+)x:h(\\d+):scale(@[\\.\\d]+x)?.:format([\\w]+)?"
    - "/:src([A-Za-z][-A-Za-z0-9_]*)/:z(\\d+)/:x(\\d+)/:y(\\d+):scale(@[\\.\\d]+x)?.:format([\\w]+)"
    formats: [png,json,headers,svg,jpeg]
    scales: [1.3, 1.5, 2, 2.6, 3]
    # Source could be either an ID, or the object describing the source
    source: gen

sources: # a path to a file, or an object with source configurations
  gen:
    protocol: bridge
    xml: "/path/to/file.xml"
    params:
      # Just as before, each param could be a string/number/boolean,
      # or an object with a single key, e.g. "ref" for a source ID, or "source" for in-place source initialization
      backend:
        source:
          ...

variables: # a path to a file, or an object with variables
  varA: value
```
